# Generated by Django 4.2.5 on 2023-09-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_user_data_delete_user_datas'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_datas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('mail', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('confirmpassword', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='User_data',
        ),
    ]
